DROP DATABASE IF EXISTS EMPLOYEETRACKER;

CREATE DATABASE EMPLOYEETRACKER;

USE EMPLOYEETRACKER;

CREATE TABLE DEPARTMENT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30)
);
CREATE TABLE ROLES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(30),
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INT REFERENCES DEPARTMENT(ID)
);


CREATE TABLE EMPLOYEES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    ROLE_ID INT REFERENCES ROLES(ID),
    MANAGER_ID INT REFERENCES EMPLOYEES(ID) ON DELETE SET NULL
);
